name: Run Telegram Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip list
    
    - name: Check environment
      run: |
        echo "Python version:"
        python --version
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
        echo "Bot token length:"
        python -c "import os; token = os.getenv('BOT_TOKEN', ''); print(f'Token length: {len(token)}')"
    
    - name: Run bot
      run: |
        python -u telegram_name_monitor_bot.py
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}